### ISSUE TITLE
Wierd Goat takes the place of Players heads in 1.19.4 Paper server

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/HoloPlots#128]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Wierd Goat takes the place of Players heads in 1.19.4 Paper server

### To Reproduce

Run server Paper 1.19.4
Goto plot world
Use new updated holographicdisplays-plugin-3.0.2-SNAPSHOT , developer version from Jenkins or compile with all fixes applied
https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

### Expected behaviour

Holo Player head , not a Holo Goat

### Screenshots / Videos

![2023-03-22_17 37 23](https://user-images.githubusercontent.com/22108822/227077600-525d4dd8-a1e5-458d-b2c8-2619b34361c5.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d832028d2abb485fb2b541b7133a1b3b

### HoloPlots Version

HoloPlots-6.2.2-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Are you sure that's not due to CustomModelData or your Resourcepack? Kind of odd, as we just delegate to HolographicDisplays.

**Comment by Tsoccerguy3** [comment]
![2023-03-23_23 39 59](https://user-images.githubusercontent.com/22108822/227419386-ee00efa5-6582-4d7d-a537-ce93a2422b9d.png)
All packs removed

**Comment by Tsoccerguy3** [comment]
[latest.log](https://github.com/IntellectualSites/HoloPlots/files/11058248/latest.log)

**Comment by Tsoccerguy3** [comment]
Not sure but this may be the cause 

https://github.com/dmulloy2/ProtocolLib/issues/2244

**Comment by Tsoccerguy3** [comment]
> Are you sure that's not due to CustomModelData or your Resourcepack? Kind of odd, as we just delegate to HolographicDisplays.

Can I get a copy of your Holoplots build that has protocolLib dependency removed , for testing .

**Comment by Tsoccerguy3** [comment]
https://github.com/filoghost/HolographicDisplays/issues/690

**Comment by PlayGlowCraft** [comment]
Tsoccer can confirm same issue on my server am Showing a Goat intead of head

**Comment by Tsoccerguy3** [comment]
Fixed in Latest Holographic displays develelopment build . Now supports 1.19.4
get it here https://ci.codemc.io/job/filoghost/job/HolographicDisplays/
