### ISSUE TITLE
[BUG] Not working as intended on Paper 1.20.4

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/HoloPlots#166]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Holoplots is placing a Iron Golem instead of players head on plot
markers . Using Holographic Display for 1.20.4 Pull request. Please note that the author has stated on their page to migrate to another Hologram plugin .
Read https://dev.bukkit.org/projects/holographic-displays at the top of page

### To Reproduce

Compile the Developer Pull request 1.20.4 from its GitHub Repository.
Run with latest Paper 1.20.4 build

### Expected behavior

Display player head

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0cd59ea3598941ca9683edbeca9ba77b

### HoloPlots Version

HoloPlots-7.0.1-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

**Comment by Tsoccerguy3** [comment]
![2023-12-14_20 27 47](https://github.com/IntellectualSites/HoloPlots/assets/22108822/49584181-cd4e-4b81-9bc3-d8c21c99b50c)

**Comment by Tsoccerguy3** [comment]
Because Holographic Display in not being maintained , This replacement was mentioned by author https://github.com/IntellectualSites/HoloPlots/issues/48

**Comment by rayanbzd** [comment]
Not an issue from HoloPlots but from HolographicDisplays. 
Just pushed a fix in the 1.20.4 support PR.
