### ISSUE TITLE
[BUG] Warnings on Paper 1.20.4 about profile name being null

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/HoloPlots#167]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Warning when players are in plot
[server_log.txt](https://github.com/IntellectualSites/HoloPlots/files/13694370/server_log.txt)

### To Reproduce

Use Hololographicdisplay PR 1.20.3 and 1.20.4 fixed ID and Paper 1.20.4 build 329

### Expected behaviour

No warnings

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ca7ad6ee50fa49f1b4bb3d1d0dcd5135

### HoloPlots Version

HoloPlots-7.0.1-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Quite interesting that the name of an OfflinePlayer is unknown to the server while the actual player is online (for quite a bit as well)

**Comment by Tsoccerguy3** [comment]
You will notice that when you remove Holoplots , the warnings stop. maybe the player heads are treated as Payers.

**Comment by PierreSchwang** [comment]
> You will notice that when you remove Holoplots , the warnings stop. maybe the player heads are treated as Payers. 

Yeah, no - I see where the error originates from, it's definitely HoloPlots. Based on the CraftBukkit implementation that's just quite weird as the player is already only. Either way, I guess for Heads the ImpromptuUUID Pipeline of PS should be utilized as well (just as a note for me or others to fix that)

**Comment by Tsoccerguy3** [comment]
Is their an ETA for a Fix ?

**Comment by OneLiteFeather** [comment]
> Quite interesting that the name of an OfflinePlayer is unknown to the server while the actual player is online (for quite a bit as well)
Well by any chance, is the player configuation phase a thing here or not? I've seen some plugins having trouble with that, as it is still "new"

**Comment by PierreSchwang** [comment]
> Is their an ETA for a Fix ?

Oh yea, I'm working on it - I'll have to clean up the remaining changes. Will be part of #48 due to missing v7 changes in that PR
