### ISSUE TITLE
Holo dont update after buy

### ISSUE THREAD

**Issue by XiNaru** [IntellectualSites/HoloPlots#171]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

i have set the price flag, an second player buy the plot and after that the holo says owner is the other chara, but not the buyer

### To Reproduce

set flag price, and buy with other chara

### Expected behaviour

holo must be updated

### Screenshots / Videos

https://images.xinaru.de/index.php/s/RkZDwdADzmtDG4K/preview

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7cdf7da3cacb4a9286375f1379f8ab64

### HoloPlots Version

7.0.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

**Comment by XiNaru** [comment]
addition: after server restart the holo is updated

**Comment by PierreSchwang** [comment]
Rework fixes deletion of holograms. 

Missing update is due to buying - not claiming - the plot, which does not fire any events. New event required in PlotSquared to hook into.

**Comment by XiNaru** [comment]
After Trying Rework:

The second problem:

The textures of the heads are not always displayed correctly. After restarting the server, for example, the skin has disappeared and only the MC default skin remains.

https://images.xinaru.de/index.php/s/xnqBcgYQbntX4Wb/preview



With the old/normal version, this dont happend. the heads there show always correctly, unless after buying/selling

**Comment by NotMyFault** [comment]
cc @PierreSchwang ref https://github.com/IntellectualSites/PlotSquared/pull/4291#issuecomment-1902645883
