### ISSUE TITLE
Failed to update hologram

### ISSUE THREAD

**Issue by TabZz147** [IntellectualSites/HoloPlots#184]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Server Version 1.20.4 (i cant choose more than 1.19.3, but Plugin Supported 1.20 too)
I have 3 Versions:
1. plots with working HoloPlots (with Holo and Skull)
2. plots with Holo (without Skull)
3. plots with nothing (no Holo, no Skull)

### To Reproduce

i have no info, why.

### Expected behaviour

Plots with Issue, i get messages like this in console:
"[Server] ERROR [HoloPlots] Failed to update hologram @ Plotwelt;2;-1"

### Error log (if applicable)

https://paste.gg/p/anonymous/fc030d896d83418da598455f1eb533e1

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/606b78f6c81b4b278d905c7b1900aa8a

### HoloPlots Version

7.1.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Update DecentHolograms. I've created a PR for it at their repo, which was merged: https://github.com/DecentSoftware-eu/DecentHolograms/pull/182

**Comment by PierreSchwang** [comment]
> Update DecentHolograms. I've created a PR for it at their repo, which was merged: https://github.com/DecentSoftware-eu/DecentHolograms/pull/182

Ah I see, no release was cut yet - nor an update released on SpigotMC. Either you build DH yourself or ask the author to create a new version with the fix.
