### ISSUE TITLE
Bug latest version of Holoplot and decentholograms

### ISSUE THREAD

**Issue by Link0Darck** [IntellectualSites/HoloPlots#192]
### Server Implementation

Spigot

### Server Version

1.20.6

### Describe the bug

Hello newbies,
Please don't close the ticket quickly :)
This is a lack of respect especially I had another problem but I could not respond to your message.

I meant that I updated Holoplot and also Decentholograms are both at the latest version in 1.20.6 spigot.

### To Reproduce

1. Update plugins.
2. /plot delete
3. /plot claim
error in console

### Expected behaviour

that the head appears

### Screenshots / Videos

![2024-05-19_03 33 30](https://github.com/IntellectualSites/HoloPlots/assets/28543376/1b4f8d58-8ef8-492e-aa9f-583f05d6b52d)

### Error log (if applicable)

https://paste.gg/p/anonymous/bdc85a002c214c39996f5be9df9d73ff

### Plot Debugpaste

No you would not have his information reasons the information is not hidden and he has personal information

### HoloPlots Version

HoloPlots version 7.1.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

### Anything else?

Spigot lasted 1.20.6

**Comment by PierreSchwang** [comment]
If you want to have respect, do me respect first and read what I explicitly said: that is no error by HoloPlots or PlotSquared. That is an internal error by DecentHolograms. That's the wrong location to report those errors.
