### ISSUE TITLE
holo

### ISSUE THREAD

**Issue by Shucai99** [IntellectualSites/HoloPlots#20]
my  problem is if i Merge  a plot  or remove it  the holos don t remove how i can fixt it thx

# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Minecraft Version:
**select one**

- [] Minecraft 1.14.4 ***This is the ONLY actively maintained target for HoloPlots***
- [] Minecraft 1.13.2

### Server build info: 

```
paste here, between the tick marks, replacing this text
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [] WorldEdit *version*: 

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/boy0001/HoloPlots/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [] I made sure I am using an up-to-date version of HoloPlots
- [] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
Fixed in 1b753351ae6659c15b8455a7101ee9797c088b6f
