### ISSUE TITLE
[Feature] Support Decent Holograms 

### ISSUE THREAD

**Issue by MrTokyo12345** [IntellectualSites/HoloPlots#48]
### What feature do you want to see added?

Support for Decent Holograms 

### Are there any alternatives?

Support for Decent Holograms 
I would like decent hologram support, as the plugin only works with HolographicDisplays

**Comment by NotMyFault** [comment]
What are "Decent Holograms" ? Some more information what that is and why it should be added may be good to know.

**Comment by MrTokyo12345** [comment]
I would like decent hologram support, as the plugin only works with HolographicDisplays

**Comment by PierreSchwang** [comment]
> I would like decent hologram support, as the plugin only works with HolographicDisplays

I started to work on that, but dumped that idea - I'm not sure if the overhead of version management and NMS would be in the scope of HoloPlots.

**Comment by NotMyFault** [comment]
If it is [this](https://www.spigotmc.org/resources/decent-holograms-placeholderapi-support-no-dependencies.96927/) plugin, I'm not against adding another optional dependency, but not in the state the plugin is currently in. For example, missing industry standards, like deploying your API to a maven repository, e.g. the central repository. Not to mention the NMS shenanigans this plugin would pull in.
Considering it's still still pretty new-ish, I would give it some time to evolve and revisit it at a later spot, when it presents a larger market share and third party interactions are standardized.

**Comment by MrTokyo12345** [comment]
Hi, when will it be added? the plugin looks very complete right now also achieved Total Downloads: 8,412

**Comment by NotMyFault** [comment]
Whenever someone wants to work on it, we're always open to any contribution.

**Comment by MrTokyo12345** [comment]
Hi any news?
