### ISSUE TITLE
HoloPlots does not work with HolographicDisplays 3.x

### ISSUE THREAD

**Issue by Sylensky** [IntellectualSites/HoloPlots#64]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Upon plot claiming no hologram is being placed above the claim sign.
Previously claimed plots get a hologram after a server restart. 

### To Reproduce

1. upload plotsquared v6.2.2
2. upload holographicdisplays 3.0.0
3. upload protocollib 4.8.0-b538
2. upload holoplots 6.2.1
3. check already claimed plots if they have a hologram
4. claim a new plot and observe that no hologram is being placed

### Expected behaviour

When a new plot is claimed a hologram should be placed above the sign.

### Screenshots / Videos

https://user-images.githubusercontent.com/57076968/147886361-09c6c8da-b50a-4e5b-943d-017532ce06a8.mp4

### Error log (if applicable)

no errors in the log with debug enabled

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a2b6ec73c9784608b26cb97db1920b68

### HoloPlots Version

6.2.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

**Comment by NotMyFault** [comment]
It looks like HoloPlots is not updated to the latest changes of HolographicDisplays 3.x
We are still using 2.x

**Comment by Fefedu973** [comment]
when is it going to be fixed ??

**Comment by PierreSchwang** [comment]
HD only released v3 beta snapshots, I'm not sure if those are considered stable and if the api design stays that way til 3.0 release

**Comment by NotMyFault** [comment]
I'd rather not depend on the snapshots, even if they are considered as stable, they are snapshots for a reason and we will treat them like that.
Once v3 has been released a stable build that is no snapshot, someone can revisit this issue, until then it remains stalled.

**Comment by Fefedu973** [comment]
Is the project still maintained ?

**Comment by NotMyFault** [comment]
> Is the project still maintained ?

Yes, but HolographicDisplays didn't release a stable version yet, therefore we can't continue here.

**Comment by NotMyFault** [comment]
I currently have no capacity to look into updating this plugin, but I can review a pull request, if someone would want to help out.

**Comment by Fefedu973** [comment]
seems to be fixed but the head is spining 
![image](https://user-images.githubusercontent.com/80718477/218076446-371cedd7-5336-499d-8c5a-fc7f1d1ac820.png)
