### ISSUE TITLE
Uncaught exception in thread Profile Lookup Executor

### ISSUE THREAD

**Issue by BensaTV** [IntellectualSites/HoloPlots#73]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Plugin is spamming constantly the following error in Console.

### To Reproduce

Install Plugin with latest Paper, HoloGraphicDisplays, ProtocolLib & PlotSquared version.

### Expected behaviour

Plugin should not throw error.

### Error log (if applicable)

https://paste.gg/p/anonymous/b06dd764002a40589f8b792d5c6d90ef

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/bf55b5ca61b24b979a47772a57b4e18a

### HoloPlots Version

6.2.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

**Comment by dordsor21** [comment]
Doesn't look like a P2 issue?

**Comment by PierreSchwang** [comment]
SkullBlockEntity is a block placed within the world, not a hologram.

**Comment by BensaTV** [comment]
Disabled CustomHeads and it's still hapening.
